query PokemonSpeciesDetail($id: Int!) {
  pokemon_v2_pokemonspecies(where: { id: { _eq: $id } }, limit: 1) {
    id
    name
    gender_rate
    capture_rate
    base_happiness
    hatch_counter
    evolution_chain_id
    pokemon_v2_generation {
      id
      pokemon_v2_generationnames(where: { language_id: { _eq: 9 } }) {
        name
      }
    }
    pokemon_v2_growthrate {
      name
    }
    pokemon_v2_pokemonspeciesnames(where: { language_id: { _eq: 9 } }) {
      name
      genus
    }
    pokemon_v2_pokemonspeciesflavortexts(
      where: { language_id: { _eq: 9 } }
      order_by: { version_id: asc }
    ) {
      flavor_text
      version_id
      pokemon_v2_version {
        id
        pokemon_v2_versionnames(where: { language_id: { _eq: 9 } }) {
          name
        }
      }
    }
    pokemon_v2_pokemoncolor {
      name
    }
    pokemon_v2_pokemonhabitat {
      name
    }
    pokemon_v2_pokemonshape {
      name
    }
    pokemon_v2_pokemonegggroups {
      pokemon_v2_egggroup {
        name
      }
    }
    pokemon_v2_evolutionchain {
      id
      pokemon_v2_pokemonspecies(order_by: { id: asc }) {
        id
        name
      }
    }
    pokemon_v2_pokemons(where: { is_default: { _eq: true } }, limit: 1) {
      id
      height
      weight
      base_experience
      pokemon_v2_pokemonsprites {
        sprites
      }
      pokemon_v2_pokemonabilities(order_by: { slot: asc }) {
        is_hidden
        slot
        pokemon_v2_ability {
          name
          pokemon_v2_abilitynames(where: { language_id: { _eq: 9 } }) {
            name
          }
        }
      }
      pokemon_v2_pokemonstats(order_by: { stat_id: asc }) {
        base_stat
        pokemon_v2_stat {
          name
        }
      }
      pokemon_v2_pokemontypes(order_by: { slot: asc }) {
        slot
        pokemon_v2_type {
          name
        }
      }
    }
  }
}
