/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from "@App/services/types.generated";

import { api } from "@App/services/baseApi";
export type GetAllTypesQueryVariables = Types.Exact<{ [key: string]: never }>;

export type GetAllTypesQuery = {
    __typename?: "query_root";
    pokemon_v2_type: Array<{
        __typename?: "pokemon_v2_type";
        id: number;
        name: string;
        move_damage_class_id?: number;
        generation_id?: number;
    }>;
};

export const GetAllTypesDocument = `
    query GetAllTypes {
  pokemon_v2_type {
    id
    name
    move_damage_class_id
    generation_id
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
    endpoints: (build) => ({
        GetAllTypes: build.query<
            GetAllTypesQuery,
            GetAllTypesQueryVariables | void
        >({
            query: (variables) => ({
                document: GetAllTypesDocument,
                variables,
            }),
        }),
    }),
});

export { injectedRtkApi as api };
export const { useGetAllTypesQuery, useLazyGetAllTypesQuery } = injectedRtkApi;
