/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from "@App/services/types.generated";

import { api } from "@App/services/baseApi";
export type GetAllGenerationsQueryVariables = Types.Exact<{
    [key: string]: never;
}>;

export type GetAllGenerationsQuery = {
    __typename?: "query_root";
    pokemon_v2_generation: Array<{
        __typename?: "pokemon_v2_generation";
        id: number;
        name: string;
        region_id?: number;
    }>;
};

export const GetAllGenerationsDocument = `
    query GetAllGenerations {
  pokemon_v2_generation {
    id
    name
    region_id
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
    endpoints: (build) => ({
        GetAllGenerations: build.query<
            GetAllGenerationsQuery,
            GetAllGenerationsQueryVariables | void
        >({
            query: (variables) => ({
                document: GetAllGenerationsDocument,
                variables,
            }),
        }),
    }),
});

export { injectedRtkApi as api };
export const { useGetAllGenerationsQuery, useLazyGetAllGenerationsQuery } =
    injectedRtkApi;
