/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../@App/services/types.generated';

import { api } from '@App/services/baseApi';
export type GetAllSpeciesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetAllSpeciesQuery = { __typename?: 'query_root', pokemon_v2_pokemonspecies: Array<{ __typename?: 'pokemon_v2_pokemonspecies', name: string, id: number }> };


export const GetAllSpeciesDocument = `
    query GetAllSpecies {
  pokemon_v2_pokemonspecies {
    name
    id
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    GetAllSpecies: build.query<GetAllSpeciesQuery, GetAllSpeciesQueryVariables | void>({
      query: (variables) => ({ document: GetAllSpeciesDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useGetAllSpeciesQuery, useLazyGetAllSpeciesQuery } = injectedRtkApi;

