/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from "@App/services/types.generated";

import { api } from "@App/services/baseApi";
export type GetAllVersionGroupsQueryVariables = Types.Exact<{
    [key: string]: never;
}>;

export type GetAllVersionGroupsQuery = {
    __typename?: "query_root";
    pokemon_v2_versiongroup: Array<{
        __typename?: "pokemon_v2_versiongroup";
        order?: number;
        name: string;
        id: number;
        generation_id?: number;
    }>;
};

export const GetAllVersionGroupsDocument = `
    query GetAllVersionGroups {
  pokemon_v2_versiongroup {
    order
    name
    id
    generation_id
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
    endpoints: (build) => ({
        GetAllVersionGroups: build.query<
            GetAllVersionGroupsQuery,
            GetAllVersionGroupsQueryVariables | void
        >({
            query: (variables) => ({
                document: GetAllVersionGroupsDocument,
                variables,
            }),
        }),
    }),
});

export { injectedRtkApi as api };
export const { useGetAllVersionGroupsQuery, useLazyGetAllVersionGroupsQuery } =
    injectedRtkApi;
