/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from "@App/services/types.generated";

import { api } from "@App/services/baseApi";
export type GetFilteredPokemonQueryVariables = Types.Exact<{
    versionGroupId?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
    generationId?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
    typeId?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>;

export type GetFilteredPokemonQuery = {
    __typename?: "query_root";
    pokemon_v2_pokemonspecies: Array<{
        __typename?: "pokemon_v2_pokemonspecies";
        base_happiness?: number;
        capture_rate?: number;
        evolution_chain_id?: number;
        evolves_from_species_id?: number;
        forms_switchable: boolean;
        gender_rate?: number;
        generation_id?: number;
        growth_rate_id?: number;
        has_gender_differences: boolean;
        hatch_counter?: number;
        id: number;
        is_baby: boolean;
        is_legendary: boolean;
        is_mythical: boolean;
        name: string;
        order?: number;
        pokemon_v2_pokemons: Array<{
            __typename?: "pokemon_v2_pokemon";
            pokemon_v2_pokemontypes: Array<{
                __typename?: "pokemon_v2_pokemontype";
                id: number;
                pokemon_id?: number;
                slot: number;
                type_id?: number;
            }>;
            pokemon_v2_pokemonsprites: Array<{
                __typename?: "pokemon_v2_pokemonsprites";
                sprites: any;
                pokemon_id?: number;
                id: number;
            }>;
        }>;
    }>;
};

export const GetFilteredPokemonDocument = `
    query GetFilteredPokemon($versionGroupId: Int, $generationId: Int, $typeId: Int) {
  pokemon_v2_pokemonspecies(
    where: {generation_id: {_eq: $generationId}, pokemon_v2_generation: {pokemon_v2_versiongroups: {id: {_eq: $generationId}}}, pokemon_v2_pokemons: {pokemon_v2_pokemontypes: {type_id: {_eq: $typeId}}}}
  ) {
    base_happiness
    capture_rate
    evolution_chain_id
    evolves_from_species_id
    forms_switchable
    gender_rate
    generation_id
    growth_rate_id
    has_gender_differences
    hatch_counter
    id
    is_baby
    is_legendary
    is_mythical
    name
    order
    pokemon_v2_pokemons {
      pokemon_v2_pokemontypes {
        id
        pokemon_id
        slot
        type_id
      }
      pokemon_v2_pokemonsprites {
        sprites(path: "other.official-artwork")
        pokemon_id
        id
      }
    }
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
    endpoints: (build) => ({
        GetFilteredPokemon: build.query<
            GetFilteredPokemonQuery,
            GetFilteredPokemonQueryVariables | void
        >({
            query: (variables) => ({
                document: GetFilteredPokemonDocument,
                variables,
            }),
        }),
    }),
});

export { injectedRtkApi as api };
export const { useGetFilteredPokemonQuery, useLazyGetFilteredPokemonQuery } =
    injectedRtkApi;
