/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from "@App/services/types.generated";

import { api } from "@App/services/baseApi";
export type AllPokemonSpeciesWithSpritesQueryVariables = Types.Exact<{
    [key: string]: never;
}>;

export type AllPokemonSpeciesWithSpritesQuery = {
    __typename?: "query_root";
    pokemon_v2_pokemonspecies: Array<{
        __typename?: "pokemon_v2_pokemonspecies";
        name: string;
        id: number;
        has_gender_differences: boolean;
        capture_rate?: number;
        base_happiness?: number;
        pokemon_v2_pokemondexnumbers: Array<{
            __typename?: "pokemon_v2_pokemondexnumber";
            pokemon_v2_pokedex?: {
                __typename?: "pokemon_v2_pokedex";
                name: string;
                id: number;
                is_main_series: boolean;
            };
        }>;
        pokemon_v2_pokemons: Array<{
            __typename?: "pokemon_v2_pokemon";
            pokemon_v2_pokemonsprites: Array<{
                __typename?: "pokemon_v2_pokemonsprites";
                sprites: any;
            }>;
            pokemon_v2_pokemontypes: Array<{
                __typename?: "pokemon_v2_pokemontype";
                pokemon_v2_type?: {
                    __typename?: "pokemon_v2_type";
                    name: string;
                    generation_id?: number;
                };
            }>;
        }>;
    }>;
};

export const AllPokemonSpeciesWithSpritesDocument = `
    query allPokemonSpeciesWithSprites {
  pokemon_v2_pokemonspecies(order_by: {id: asc}) {
    name
    id
    pokemon_v2_pokemondexnumbers {
      pokemon_v2_pokedex {
        name
        id
        is_main_series
      }
    }
    pokemon_v2_pokemons {
      pokemon_v2_pokemonsprites {
        sprites(path: "other.official-artwork")
      }
      pokemon_v2_pokemontypes {
        pokemon_v2_type {
          name
          generation_id
        }
      }
    }
    has_gender_differences
    capture_rate
    base_happiness
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
    endpoints: (build) => ({
        allPokemonSpeciesWithSprites: build.query<
            AllPokemonSpeciesWithSpritesQuery,
            AllPokemonSpeciesWithSpritesQueryVariables | void
        >({
            query: (variables) => ({
                document: AllPokemonSpeciesWithSpritesDocument,
                variables,
            }),
        }),
    }),
});

export { injectedRtkApi as api };
export const {
    useAllPokemonSpeciesWithSpritesQuery,
    useLazyAllPokemonSpeciesWithSpritesQuery,
} = injectedRtkApi;
